server:
  port: 8083
  ssl:
    enabled: false

endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true

spring:
  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/login"
    username: postgres
    password: postgresql
      #security:
      # oauth2:
      #  client:
      #   registration:
      #  google:
    #    clientId: 1024095120816-bt34rhqq074evbk2tf5hd03uqokq5n9b.apps.googleusercontent.com
    #    clientSecret: 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

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
logging.level.org.springframework.web.client.RestTemplate: DEBUG